# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                       STORAGE SETTINGS                                       | #
# |                                                                                              | #
# |                Controls which storage method NoDataSync will use to store data.        | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# How the plugin should store data
#
# - Possible options:
#
#   |  Remote databases - require connection information to be configured below
#   |=> PostgreSQL
#
# - A PostgreSQL database is the default option.
data-storage-method: PotgreSQL

session-storage-method: Redis

# The following block defines the settings for remote database storage methods.
#
data:
  postgresql:
    # Define the address and port for the database.
    # - The standard DB engine port is used by default
    #   (PostgreSQL: 5432)
    # - Specify as "host:port" if differs
    address: 'localhost:5432'

    # The name of the database to store NoDataSync data in.
    # - This must be created already. Don't worry about this setting if you're using MongoDB.
    database: 'bungeeauth'

    # Credentials for the database.
    username: 'bungeeauth'
    password: 'password'

    # These settings apply to the MySQL connection pool.
    # - The default values will be suitable for the majority of users.
    # - Do not change these settings unless you know what you're doing!
    pool-settings:

      # Sets the maximum size of the MySQL connection pool.
      # - Basically this value will determine the maximum number of actual
      #   connections to the database backend.
      # - More information about determining the size of connection pools can be found here:
      #   https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
      maximum-pool-size: 10

      # Sets the minimum number of idle connections that the pool will try to maintain.
      # - For maximum performance and responsiveness to spike demands, it is recommended to not set
      #   this value and instead allow the pool to act as a fixed size connection pool.
      #   (set this value to the same as 'maximum-pool-size')
      minimum-idle: 10

      # This setting controls the maximum lifetime of a connection in the pool in milliseconds.
      # - The value should be at least 30 seconds less than any database or infrastructure imposed
      #   connection time limit.
      maximum-lifetime: 1800000 # 30 minutes

      # This setting controls the maximum number of milliseconds that the plugin will wait for a
      # connection from the pool, before timing out.
      connection-timeout: 5000 # 5 seconds

      # This setting allows you to define extra properties for connections.
      #
      # By default, the following options are set to enable utf8 encoding. (you may need to remove
      # these if you are using PostgreSQL)
      #   useUnicode: true
      #   characterEncoding: utf8
      #
      # You can also use this section to disable SSL connections, by uncommenting the 'useSSL' and
      # 'verifyServerCertificate' options below.
      properties:
        #useUnicode: true
        #characterEncoding: utf8
        #useSSL: false
        #verifyServerCertificate: false

  # The prefix for all NoDataSync SQL tables.
  # - Change this if you want to use different tables for different servers.
  table-prefix: 'bungeeauth_'

# The following block defines the settings for remote database cache storage methods.
#
session:

  lifetime: 602000 # 7 days

  redis:
    # Define the address and port for the database.
    # - The standard Redis port is used by default (Default: 6379)
    # - Specify as "host:port" if differs
    address: '${REDIS_HOST}:${REDIS_PORT}'

    # The number of the database to store data.
    # Default: 0
    database: null # ignored for type Redis

    # Default: null
    password: '${REDIS_PASS}'

    # These settings apply to the MySQL connection pool.
    # - The default values will be suitable for the majority of users.
    # - Do not change these settings unless you know what you're doing!
    pool-settings:

      # Sets the maximum size of the Redis connection pool.
      # - Basically this value will determine the maximum number of actual
      #   connections to the database backend.
      maximum-pool-size: 10000

      # This setting controls the maximum number of milliseconds that the plugin will wait for a
      # connection from the pool, before timing out.
      connection-timeout: 5000 # 5 seconds

    # The main channel prefix.
    channel: 'bungeeauth' # DO NOT TOUCH IT IF YOU DON'T KNOW ABOUT THIS OPTION

settings:
  max-auth-attempts: 6
  max-auth-time: 500
  ban-time-minutes: 10
  min-password-length: 4

white-list:
  na01:
    - '134.249.237.221'

servers:
  # servers which accept player after login
  game:
    - 'earth'
  # servers for login players
  login:
    - 'login'

# can be SHA256, SHA1, BCRYPT
hash-method: BCRYPT

# allowed protocols to join
allowed-protocols: '^73(5|6)$'